### PR TITLE
Wishlist page

### PR DESCRIPTION
**Pull request by rahulyadav139**
Wishlist page is here for the e-com site. Review it.

### CODE REVIEW

**Review by j24m — APPROVED** [review]

**Review by j24m — APPROVED** [review]

**Review by PuneetP16 — APPROVED** [review]
LGTM.

**Review by j24m — APPROVED** [review]
Code is fine, but you can maybe change the color of footer and keep it same as the color of 
blue shade button, and don't use so many colors at the same time, you can also remove the background color from star rating and give the star a yellow color and keep the font beside star black.
This is just a suggestion, rest is your choice. The color of remove button(The font and the border color ) can be same as that of the primary button. Again it's your choice at the end.

**Comment by rahulyadav139** [comment]
> Code is fine, but you can maybe change the color of footer and keep it same as the color of blue shade button, and don't use so many colors at the same time, you can also remove the background color from star rating and give the star a yellow color and keep the font beside star black. This is just a suggestion, rest is your choice. The color of remove button(The font and the border color ) can be same as that of the primary button. Again it's your choice at the end.

Thank you for the suggestions Jyotsna. These are such priceless but for now, I am going with the same. If I get some more time then I will try to make these changes, and if these look good then I'll go with the suggestions.

**Comment by rahulyadav139** [comment]
Thank for the reviews.

**Pull request merged**
